### ISSUE TITLE
AGS-CL for more complex architectures?

### ISSUE THREAD

**Issue by toshi2k2** [sangwon79/AGS-CL#2]
Will it be possible to trivially implement AGS-Cl for a more complex architecture - say Resnet18?

**Comment by hongjoon0805** [comment]
Due to the identity mapping part in ResNet architecture, it is hard to naively implement AGS-CL algorithm with PGD. However, if we add simple scaling parameters in the identity mapping part , it is possible to train AGS-CL with PGD.
The simply modified identity part of ResNet is as follows:

For C channels,
h = F(x) + **a** * x, **a** = {a_i}_{i=1}^C, and
F(x) is a convolution layer which consists of weights {**W**__i_}_{i=1}^C

By defining a_i and **W**_i as groups, applying PGD can guarantee the zero-valued channel if both a_i and **W**_i are zero.

Therefore, with simple modification, implementing AGS-CL for a more complex architecture such as ResNet is possible.
